// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numTimes = Integer.parseInt(args[0]);
		int countUnderHalf = 0;
		int countHalfOrOver = 0;
		double randomNum = 0;
		float ratio = 0;

		for (int i = 0; i < numTimes; i++) {
			randomNum = Math.random();
			 
			if (randomNum < 0.5) {
				countUnderHalf ++;
			}

			else {
				countHalfOrOver ++;
			}
		}

		System.out.println("> 0.5: "+ countUnderHalf + " times");
		System.out.println("<= 0.5: "+ countHalfOrOver + " times");
		
		if (countHalfOrOver != 0){
			ratio = (float) countUnderHalf / countHalfOrOver;
			System.out.println("Ratio: " + ratio);
		}
	}
}
